### ISSUE TITLE
Can I use this plugin as code in a Cloud Function?

### ISSUE THREAD

**Issue by bes** [traviswt/gke-auth-plugin#3]
Hi,

I have upgraded a Cloud Function (out of necessity) to use `k8s.io/client-go v0.28.0-rc.0`, and as you know it says to `Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.`, which I can't because this is a Cloud Function with a very limited environment.

Can I use `gke-auth-plugin` in this environment somehow?

I guess what I need to do is to replace this line:

```
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

With something from this project, if possible?

Thanks!

**Comment by traviswt** [comment]
The client-go requires the ability to "exec" a plugin, which is why this is a binary. There doesn't appear to be a way to use the client-go auth plugin mechanics without the ability to "exec". You could look into client-go and see if you can bypass the plugin mechanism when generating your connection so that way you could leverage some of the concepts here, but unfortunately, the way this plugin is configured, it requires stdin->stdout handshaking and makes a lot of assumptions about disk, storage, and runtime context. See this for more information about what client-go can and can't do today: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

**Comment by bes** [comment]
Thanks, I have abandoned this idea :)
